
name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/6 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "clionl@qq.com"
          git config --local user.name "clionl"
          git remote set-url origin https://github.com/clionl/tryagain
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
